### ISSUE TITLE
Respond to multiple hostnames

### ISSUE THREAD

**Issue by fhunleth** [pcmarks/mdns_lite#32]
Here's what I'd like to do:

```elixir
config :mdns_lite,
  mdns_config: %{
    host: [:hostname, "nerves"]
  }
```

For Nerves training classes and getting started guides, it has been really convenient to have people connect to `nerves.local`. This gets rid of needing to know serial numbers that aren't printed anywhere on a Raspberry Pi. 

However, "nerves.local" becomes much less useful when there's a second device. It would be really nice to also support the `:hostname` identification out of the box so that it's not a firmware update to switch.

Supporting multiple hosts affects service advertisements. I think that it's acceptable to say that service advertisements use the first item in the host list only. I.e., if the user tries to discover ssh servers, they'd get the `:hostname` version rather than the `"nerves"` version since `:hostname` is first in the list. I think that makes more sense - especially since if a user can run service discovery, they don't need the convenience of `"nerves.local"`.

**Comment by pcmarks** [comment]
This would now be configured as:
```elixir
config :mdns_lite,
    host: [:hostname, "nerves"]
    ...
```

**Comment by pcmarks** [comment]
It is ok to have two hostnames pointing at the same IP address, in which case an "A" query could respond with two A answers in the response - one for each hostname. However, when this reasoning is applied to other queries, especially with "PTR" queries, one can run into issues of packet size. UDP has definite size limitations on what it can send.

Therefore, the easiest way to implement the use of multiple hostnames is to treat each hostname as a separate query with its own set of responses.

**Comment by pcmarks** [comment]
While it is possible to have two answers, say, to an 'A' query, in one response, because the responses are sent as UDP packets there is always the possibility of creating a too large UDP packet.

Therefore:
    
mdns_lite will answer
 'A' queries with separate responses for each host name, 
 'PTR' (reverse lookup only) queries with separate responses for each host name. 

For all other queries, there will be only one response to the first (or only) host name.

**Comment by fhunleth** [comment]
I think the RFC has some input on this. I had the feeling like there was a preference to fewer packets. This could be a "should" and not a "must".

From what I've seen from wireshark, devices typically respond with both the IPv4 and IPv6 addresses in service responses. For 'A' query responses, I would expect that only one address, the IPv4 address, would naturally be put in the UDP packet anyway.

I'm not sure if anyone uses reverse lookup mDNS PTR queries in practice, so I doubt it matters what happens there. Even with DNS PTR queries, you get a server name that's more meaningful to someone in ops (like `ae-6.r06.asbnva02.us.bb.gin.ntt.net`) rather than something helpful. I think replying with the first name in the list would be sufficient. It doesn't feel right to have this use of mDNS penalize more common uses.

As for exceeding the UDP packet size, I don't think this is an issue for normal use. The UDP payload size close to 64K and if you want to avoid fragmentation (which I think is a good practice), you still have something like 1400 bytes. That seems like it should hold a few responses. I'm not sure what the right number is, but if it's 20 responses, then I'd prefer semantics that penalize the person who specifies 20 hostnames. I'm also worried that many mDNS clients will return immediately after they receive the first response to their query. I.e., responses after the first would be dropped.

**Comment by pcmarks** [comment]
Just so I understand:

If an A request comes in then mdns_lite would respond with an A answer for each host name. So if there are two host names then there would be two A answers in the same packet. Later for ipv6 , there would also be AAAA answers as well.

PTR requests would only respond with the first host name in the list.

**Comment by fhunleth** [comment]
An A record maps a name to an IPv4 address. If you have a configuration where `mdns_lite` is configured to respond to `nerves.local` and `nerves-1234.local`, then if a A record query comes in for `nerves.local`, it would respond with one IPv4 address. If at another time an A record query comes in for `nerves-1234.local`, then I'd expect it to respond with one IPv4 address.

It might be theoretically possible to have a multi-query request that asks for both A records. For that, I'd expect it to return both A records, but I don't think that's something that would happen in practice.

**Comment by fhunleth** [comment]
As for the PTR requests. I think that what you stated is completely fine. If a use case arises in the future that needs something more, then it seems like we'd revisit then.

**Comment by pcmarks** [comment]
OK. I get it now.
