### ISSUE TITLE
Dynamically control [debug] logging ?

### ISSUE THREAD

**Issue by jsimmonds2** [pcmarks/mdns_lite#49]
I'm 'unofficially' helping to QA the [Farmbot OS](https://github.com/FarmBot/farmbot_os) pre-release versions.
I've noticed that the **`:mdns_lite`** app is quite noisy ( on my little home network ) with **`[debug]  IGNORING`** logs which seem to come from unsupported query types in requests.

Caveat : I like debug logs . . but this one would be more useful if it identified the ip address which originated the query :)

For consumers of this package ( such as Farmbot OS )  could the debug logging be disabled dynamically some how ?

Thanks !

![image](https://user-images.githubusercontent.com/1224439/65221957-74a60b80-db01-11e9-9464-8b50d5e54778.png)

**Comment by pcmarks** [comment]
The unhelpful Logger.debug messages should be gone now.

Thank you!

**Comment by jsimmonds2** [comment]
@pcmarks, thank you for refactoring this behaviour !
I'll suggest to the FarmBot team that updating to your version **`0.4.2`** will be 'a win-win` 🙂.
